<template>
  <div class="container-wrapper">
    <h3 data-aos="fade-up" data-aos-delay="200" class="head-title">
      Work and
      <span class="span-education">Education</span>
    </h3>

    <section class="inner-container-section">
      <div data-aos="zoom-in" data-aos-delay="800" class="left-work left">
        <h4 class="mini-title">Work Experience</h4>
        <div class="experience-wrapper">
          <p
            class="mini-sub-title"
          >Junior front-end Developer - Lab08 | Sofia Bulgaria | 2020 (4 months)</p>
          <p
            class="experience-description"
          >At Lab08 I was working in a small team of very talented individuals. I was using Vue.js in tandem with the Storybook platform for developing ui components. We used them for a testing platform for a big Nordic Company.</p>
          <b>(Vue.js, StoryBook, Sass, Javascript, HTML, CSS)</b>
        </div>
        <div class="experience-wrapper">
          <p
            class="mini-sub-title"
          >Junior front-end Developer - Indeavr | Sofia Bulgaria | 2019 - 2020 (1 year)</p>
          <p
            class="experience-description"
          >In my department i was working with one specific big client and creating software for them. We were using the agile methodology. I learned a lot about front-end development here and some basic backend</p>
          <b>(Jquery, C#, HTML, CSS, Sass, Javascript)</b>
        </div>
        <div class="experience-wrapper">
          <p
            class="mini-sub-title"
          >Technical Trainer - Software university | Sofia Bulgaria | 2018 (6 months)</p>
          <p class="experience-description">
            After finishing the academy I was invited by a colleague of mine to try and lecture one course in the academy. It was trilling experience which helped me meet a lot of new and intelligent people and develop communication skills. I taught them HTML5, JavaScript, CSS, SASS.
            Here are links to two exams that I created:
            <a
              href="https://github.com/MarikMayhem/Handlebars-CarTube-Exam"
            >Link1</a>
            <a href="https://github.com/MarikMayhem/Handlebars-MemeLounge-RetakeExam">Link2</a>
          </p>
        </div>
      </div>

      <div data-aos="zoom-out" data-aos-delay="800" id="right-education" class="right">
        <h4 class="mini-title">Education</h4>
        <div class="experience-wrapper">
          <p class="mini-sub-title">Software University (Sofia) 2016-2018</p>
          <p
            class="experience-description"
          >I chose Softuni because in a way it was an alternative to the traditional education. Here I created real console applications using C#. It got really interesting to me. When I was introduced to front end development there I really liked it and JS grabbed my attention.</p>
          <b>
            (C#, JavaScript,Jquery,React,
            <br />Angular, Express, HTML, CSS, SASS, LESS)
          </b>
        </div>
        <div class="experience-wrapper">
          <p
            class="mini-sub-title"
          >Proffesional Technical High School Nicola Vasiliadi (Gabrovo) 2010-2015</p>
          <p
            class="experience-description"
          >In PTH Nikola Vasiliadi I was introduced to the programming with C++. Not the ideal language for a beginner, but it sparked my light. Later we were introduced to HTML And CSS and it got my attention. I really enjoyed making websites.</p>
          <b>(C++, Visual Basic, HTML, CSS)</b>
        </div>
      </div>
    </section>
  </div>
</template>>


<script>
</script>

<style src="./WorkAndEducation.scss" scoped lang="scss"/>
